### PR TITLE
WIP: feat(typing): use es style module export

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
This pull request change import style to ES module.

WIP, let's wait for Vue2.5.

### CODE REVIEW

**Comment by yyx990803** [comment]
@regou just a note that let's use "Squash and Merge" in the future for cleaner git logs :)

**Comment by regou** [comment]
👌

**Comment by thewei** [comment]
@yyx990803 The NPM package version is not use ES module, please publish a new version.

**Comment by yyx990803** [comment]
@thewei use 5.0 with Vue 2.5

**Pull request merged**
