### PR TITLE
Add feature eventToObservable

### PR DESCRIPTION
**Pull request by regou**
Convert vm.$on to observable

### CODE REVIEW

**Comment by yyx990803** [comment]
I think per #44 , it would be ideal that `v-stream`, when used on a component, would listen for the custom event stream instead using this new method.

It can be done by checking the presence of `vnode.componentInstance` in `v-stream`'s bind hook. If an instance is present, then the directive is being used on a custom component, and the resulting stream should be constructed differently.

**Comment by regou** [comment]
I've noticed that this Pr is irrelevant to issue #44 yesterday then deleted the github reference, but the mark still there. 
Sorry about the confusion.

#44 is about v-stream directive 
This Pr is about add event callbacks 
`v-on`       ->  `v-stream`
`vm.$on`  ->  `vm.$eventToObservable` (maybe `vm.$stream`?)

**Comment by regou** [comment]
About #44 , I tried but `vnode.componentInstance` in bind callback is aways `undefined` https://github.com/vuejs/vue-rx/blob/master/src/directives/stream.js#L5

**Comment by yyx990803** [comment]
@regou yeah, it will be `undefined` if it's used on a normal element e.g. `<button>`. It will only be defined when `v-stream` is used on a custom component, so something like:

``` js
bind (el, binding, vnode) {
  // ...
  if (vnode.componentInstance) {
    // bind using vnode.componentInstance.$eventToObservable
  } else {
    // bind using Rx.fromEvent()
  }
}
```

**Comment by regou** [comment]
Job done 💯 
But @yyx990803 , please beware : 
https://github.com/vuejs/vue-rx/pull/45/commits/911879a91421f30ec2998758e578556335cfa225
These 3 deleted lines not actually working. 
`unsub` can only unsubscribe subscriptions ( return of `.subscribe()` call )
Better add a FAQ section on Readme about how to auto unsub  #41 
- `vm.$subscribeTo`
- `subscriptions`
- `.takeUntil(vm.$eventToObservable('hook:beforeDestroy'))`

**Comment by yyx990803** [comment]
Excellent job! Thanks for the great contributions you've made to this project, I've added you as a collaborator :)

**Pull request merged**
